name: Artifact
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 7

  download:
    needs:
      - upload
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
