name: Conditions
on: push
jobs:
  skip-on-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "Hello"
        if: ${{ failure() }}
  skip-job:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'octcat' }}
    steps:
      - run: echo "Hello"
