name: Fail-fast matrix
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        time: [10, 20, 30]
    steps:
      - env:
          TIME: ${{ matrix.time }}
        run: sleep "${TIME}" && exit 1
