name: Matrix
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${RUNNER_OS}"

  multi-dimensions:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version

  include:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: 20
          - os: macos-latest
            version: 22
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version
