name: Publish
run-name: publish docker image (${{ inputs.version }})
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: バージョン(v1.2.3)
env:
  IMAGE_NAME: gha-image

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=raw,value=latest
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: docker/example
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
