name: Release
run-name: release ${{ github.ref_name }}
defaults:
  run:
    shell: bash
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod
      - name: build go binary file
        run: go build -ldflags "-X main.version=${VERSION}" -o "${RUNNER_TEMP}/example" go/main.go
      - name: create release note
        run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release update "${RUNNER_TEMP}/example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
